### ISSUE TITLE
SQL question

### ISSUE THREAD

**Issue by PIPDesign** [TouchMe-Inc/l4d2_versus_stats#3]
Your plugin is cool.Does it work properly in co-op mode？Can you provide a database table file？

**Comment by TouchMe-Inc** [comment]
Hello. Statistics in this version only work in versus and verus realism.

Game mode is checked here:
https://github.com/TouchMe-Inc/l4d2_versus_stats/blob/c1d8484f0e4f2e04eb1771ae819d8ebeecfe5280/addons/sourcemod/scripting/versus_stats.sp#L1459

SQL is built* automatically here:
https://github.com/TouchMe-Inc/l4d2_versus_stats/blob/c1d8484f0e4f2e04eb1771ae819d8ebeecfe5280/addons/sourcemod/scripting/versus_stats.sp#L899
\* The table has a non-optimal structure (100+ fields) due to the way SQL works in sourcemod
